spring.application.name=restaurant-booking
server.port=8080

# Default profile
spring.profiles.default=dev

# Common JPA settings
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# JSON formatting
spring.jackson.serialization.write-dates-as-timestamps=false